### PR TITLE
Allow to use custom request matcher

### LINKED ISSUE #206: [Feature request] Per-page CSP configuration
The clickjacking protection supports applying a different configuration for different paths. It would be great if CSP could do it as well.

See https://github.blog/2016-04-12-githubs-csp-journey/#connect-src which describes a use case that Github has for this (which is also what gave me the idea to request it here. My own CSP journey is not yet at the point where I would need it, but it might come).

### PR DESCRIPTION
**Pull request by ihmels**
This adds an option to allow the use of a custom request matcher, e.g. to exclude certain paths.

This fixes #206 partially.

### CODE REVIEW

**Comment by tooltonix** [comment]
I need this feature urgently at the moment, please merge.

**Comment by Seldaek** [comment]
This would need to be added to the docs still, and ideally it should be made clear that using this renders the `hosts` option useless/unused.

**Comment by ihmels** [comment]
@Seldaek, can you take another look at this?

**Comment by Seldaek** [comment]
Yeah, sorry we're not as responsive as we could be here.. But anyway the PR looks good to me now I think! Thanks

**Pull request merged**
