### PR TITLE
Updated config to use new setFactory method

### PR DESCRIPTION
**Pull request by jrnickell**

### CODE REVIEW

**Comment by sstok** [comment]
This is incompatible with Symfony 2.3 (no?) so this would require a major version bump or you need a compatibility layer to support both Symfony 2.3 and 2.6.

**Comment by Seldaek** [comment]
Yeah I don't really see the benefit of this change.

**Comment by jrnickell** [comment]
Granted, I can see the problem if you need to support 2.3. Unfortunately, the old syntax is causing deprecated notices in Symfony 2.7. I've suppressed them for now. Thank you

**Comment by Seldaek** [comment]
Ok yeah that's unfortunate. Sadly 2.3 is still supported for a year so we can't easily drop it. But we could maybe start a 2.0 version that supports symfony 2.7+ as that's the next LTS.. If someone is willing to do this let me know, I don't really have time. @romainneutron may be interested?

**Comment by romainneutron** [comment]
I'm sorry, I really don't have time for this now. 
I've planned to move on 2.7 soon, I could get some time thinking about this at that point.

**Comment by Seldaek** [comment]
Closing as #76 takes care of getting 2.3 and 2.6+ support working AFAIK (correct me if I'm wrong @DemonTPx)

**Pull request closed without merging**
