### PR TITLE
Symfony3 compatibility

### PR DESCRIPTION
**Pull request by DemonTPx**

### CODE REVIEW

**Comment by JordyMoos** [comment]
+1

**Comment by sstok** [comment]
:+1:

**Comment by DemonTPx** [comment]
It seems that this is not working correctly with Symfony 3.0, since `factory_class` and `factory_method` in service definitions have been replaced by `factory`. PR #65 should be merged first which requires a minimum version requirement of Symfony 2.6 in stead of 2.3.

**Comment by DemonTPx** [comment]
The bundle is now compatible with Symfony 2.3 to 3.0 by switching to a 'legacy' service file when the symfony version is lower than 2.6. It causes a little bit of duplication, but at least makes the bundle usable with Symfony 3.0

**Comment by Seldaek** [comment]
Thanks

**Pull request merged**
