### PR TITLE
remove $ so gitclip works

### PR DESCRIPTION
**Pull request by tacman**

### CODE REVIEW

**Comment by Seldaek** [comment]
At this point I'm kinda wondering if we shouldn't just PR git clip so it strips leading $ signs 😆 but thanks

**Comment by tacman** [comment]
That's right -- YOU are the guy that can do that!  I completely forgot about that solution.  

I don't like the way the $ looks, but Symfony does.  Symfony requires a triple-click on the string itself instead of a nice little "copy" icon from their own website, which I've never understood (e.g. https://symfony.com/bundles/AssetMapperTypeScriptBundle/current/index.html)

And they require the $ be in their docs. This has lead to many bundles copying this behavior, despite it not working well on composer at all.

**Comment by Seldaek** [comment]
Have you reported that on https://github.com/symfony/symfony-docs? Maybe nobody ever thought of putting a copy icon in there?

**Comment by Seldaek** [comment]
I mean they do have it for code blocks, so it seems like an omission not having it for shell commands.

**Pull request merged**
