### PR TITLE
Added support for "x-forwarded-proto" check on force SSL

### PR DESCRIPTION
**Pull request by dragosprotung**

### CODE REVIEW

**Comment by Seldaek** [comment]
I'm not sure I agree with this. If you are behind a proxy then you should rather configure the Request class's trusted headers and trusted proxies, once you do that then https forwarded proto will mark the request's isSecure() to be true and the bundle starts working as it should.

**Comment by dragosprotung** [comment]
Some proxies like Amazon elastic load balancers or Heroku do not have a fixed IP or a range to target. In this cases you can still forward to HTTPS

**Comment by Seldaek** [comment]
Well if you trust any IP Maybe you can use 0.0.0.0/0 as IP mask? Still sounds like replacing a symfony functionality with a workaround here, so I'm not a fan.

**Comment by dragosprotung** [comment]
Trusting any IP is not the end of the story. I still want to send the redirect header if the `X-FORWARDED-PROTO` header is not present. The reverse proxy can be configured to strip away or overwrite the `X-FORWARDED-PROTO` from the client.

As an example the user goes to http://domain.com, the proxy will forward the request to application.
The listener kicks in and sends the redirect header. The browser now goes to https://domain.com
Now the proxy will forward the request to the application but still calling http://domain.com with the aditional `X-FORWARDED-PROTO: https` header. In this case we do not want to redirect yet again as it will end up in an infinite loop.

**Comment by Seldaek** [comment]
If the header is missing then it will redirect. If the header is present and indicates a secure connection then it will not redirect. Please try it. I am pretty sure this PR is not needed.

**Comment by Seldaek** [comment]
As you can see in https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L1183 - isSecure returns true if the header is present and trusted. The bundle will skip the redirect if the request isSecure returns true.

See http://symfony.com/doc/current/components/http_foundation/trusting_proxies.html for details.

**Comment by dragosprotung** [comment]
You are right. I didn't know about this in Symfony and for some reason i missed it while reading the code. This PR is not needed.

Thanks for the explanations.

**Comment by Seldaek** [comment]
No problem, glad you worked it out :)

**Pull request closed without merging**
