### PR TITLE
Upgrade the Bundle to support Symfony 5 BETA2

### PR DESCRIPTION
**Pull request by damienalexandre**
This is a work in progress, as the release of Symfony 5 is expected to the end of November. All tests are green :heavy_check_mark: on my machine.

I had to remove support for PHP 5 and older versions of Symfony, as SF5 is not compatible with SF4 (see the "conflicts" here: https://packagist.org/packages/symfony/http-kernel#v5.0.0-BETA2) and only support PHP 7...

This *could* be worked around, maybe. We could remove type hint, and add conditions on event listener arguments. I will need more time to test this.

Code changes are minor:

- new class naming
- fix for some deprecated stuffs in PHPUnit

I expect no other work to be done on release day, just a `composer.json` clean-up (removing the new lines added to force `@beta`).

### CODE REVIEW

**Comment by Seldaek** [comment]
Thanks for the work, I guess the branch-alias in composer.json should be changed to 3.x-dev though as this will require a major release.

**Comment by damienalexandre** [comment]
Yes I will change the branch-alias too.

Actually I have another branch when I try to be less agressive about the update (supporting SF 5 on top of all the other versions still supported!). It's a bit of a mess in the tests as some classes don't exists anymore, but on the listeners, I could do things like this:

```php
    public function onKernelRequest($event)
    {	    
        // Compatibility with Symfony < 5 and Symfony >=5
        if (!$event instanceof GetResponseEvent && !$event instanceof RequestEvent) {
            return;
        }
```

WDYT?

**Comment by Seldaek** [comment]
Might be easier to avoid having to maintain two branches.. we already don't have enough dev resources on this bundle. So yes please if it avoids a major release I'm all for it even if it adds a little cruft.

**Comment by damienalexandre** [comment]
This PR is superseded by #211 :+1: now that Symfony 5 is available and I've made it compatible with all versions of Symfony.

**Pull request closed without merging**
